### ISSUE TITLE
Why rewrite external script tags?

### ISSUE THREAD

**Issue by ciddan** [Menci/vite-plugin-public-path#3]
Hey!

I've got a use case where I'm dependent on certain external scripts being included in the initial DOM, in `<head>`. This plugin removes those script tags from the DOM and dynamically adds them back to the document body, which unfortunately breaks the page.

What is the purpose of rewriting external script tags? They will never be impacted by the public path, so why rewrite them?

**Comment by Menci** [comment]
My initial idea is rewriting ALL scripts ensures the right script evalution order. I didn't realized the problem.

Should I add an option to exclude *specfied* scripts completely from transforming? Or just ignore ALL external scripts?

**Comment by Menci** [comment]
Maybe it's not enough to just consider external scripts. Consider someone using jQuery from `/node_modules/jquery`?

**Comment by ciddan** [comment]
> Maybe it's not enough to just consider external scripts. Consider someone using jQuery from `/node_modules/jquery`?

Absolutely. Let me be a bit more precise. I'm specifically referring to a script that is loaded from a fully qualified domain, like this:
```html
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js"></script>
```

**Comment by ciddan** [comment]
> My initial idea is rewriting ALL scripts ensures the right script evalution order. I didn't realized the problem.
> 
> Should I add an option to exclude _specfied_ scripts completely from transforming? Or just ignore ALL external scripts?

The PR I opened excludes all absolute src script tags. If you think that's too much, then maybe an attribute hint on the tag?

**Comment by Menci** [comment]
Consider someone loading jQuery locally with `/node_modules/jquery` instead from CDN, your current solution may not be enough.

Maybe accept a selector option to let the user specify what scripts should be excluded?

**Comment by ciddan** [comment]
> Consider someone loading jQuery locally with `/node_modules/jquery` instead from CDN, your current solution may not be enough.
> 
> Maybe accept a selector option to let the user specify what scripts should be excluded?

Sorry, I was being a bit too focused on my own use case. I see what you're saying.

Simplest solution would be an attribute hint on the tag itself, but that is a bit ugly. A config property to run against the "patch properties" would remove the DOM pollution.

Want me to update my PR with a filter in the config?

**Comment by ciddan** [comment]
I've submitted an alternative PR that should cover both cases. Let me know what you think.
