### ISSUE TITLE
memory allocation of bytes failed

### ISSUE THREAD

**Issue by coure2011** [Menci/vite-plugin-public-path#6]
On my project build was working fine
But as soon as I added this plugin the build is failing for me with error `memory allocation of 268435456 bytes failed` and now I need to add  `NODE_OPTIONS=--max_old_space_size=8192`  on my local.

```
publicPath({
            // A JS expression evaluates on client side each time when loading a new file
            // Should evaluate to a string ending with "/"
            publicPathExpression: "window.publicPath",
            html: true,
            // uncomment if needed
            // excludeScripts: /^https:.*systemjs/
        }),
```

As the app is build via Github actions running which have memory of 7GB, its always failing. Even setting the max-old-space-size does not work there for windows env.

**Comment by Menci** [comment]
Did you try larger runners in https://github.blog/changelog/2022-09-01-github-actions-larger-runners-are-now-in-public-beta/?
